window.KAMEPOSU_COPY = Object.freeze({
  terms: Object.freeze({
    bag: "バッグ",
    delivery: "配達",
    home: "家",
    score: "スコア",
    combo: "連便",
  }),
  buttons: Object.freeze({
    todayDelivery: "▶ 今日の配達へ",
    rest: "ひと休み",
    retry: "もう一便",
    resume: "配達へ戻る",
    restart: "走り直す",
    back: "戻る",
  }),
  result: Object.freeze({
    finished: "配達完了",
    bestUpdated: "自己ベスト更新！",
    weeklyChampion: "今週のデイリーチャンピオン",
    bestTarget: "自己ベストまで",
    bestTie: "同じスコア",
    updated: "更新",
    highestUpdated: "最高更新",
    oneMore: "あと1",
    missionDone: "達成",
    missionLeft: "あと{count}件",
    missionLine: "今日のかめ便: {summary} / {status}",
  }),
  share: Object.freeze({
    url: "https://24-105.github.io/kameposu/",
    title: "かめぽす便",
    button: "結果をシェア",
    imageButton: "画像を保存",
    imageSaved: "画像を保存しました",
    imageFailed: "画像を作れませんでした",
    copied: "コピーしました",
    failed: "コピーできませんでした",
  }),
  ui: Object.freeze({
    ranking: "ランキング",
    rankingAria: "ランキングを見る",
    recommendations: "おすすめ",
    recommendationsAria: "おすすめゲームを見る",
    todayRanking: "今日のランキング",
    recommendBlockAria: "おすすめのゲーム",
    recommendCardAria: "おすすめゲーム",
    time: "時間",
    rank: "ランク",
    guideTitle: "バッグを甲羅にのせて家へ配達しよう！",
    dailyMission: "今日のかめ便",
    guideDemoAria: "線の見本",
    pauseTitle: "甲羅でひと休み",
    rulesAria: "基本ルール",
    controls: "操作方法",
    dragControl: "画面をなぞる",
    padControl: "下の十字キー",
    dragControlAria: "画面をなぞって操作",
    padControlAria: "下の十字キーで操作",
    nextPlay: "次に遊ぶ",
    mobileGames: "スマホで遊べる",
    play: "遊ぶ",
    turtleCourier: "カメ配達員",
    nextDelivery: "次の一便",
    turtleMemo: "かめメモ",
    resultTabsAria: "結果表示",
    deliveryMemo: "配達メモ",
    resultTargetAria: "次回の狙い",
    highlightsAria: "今回の見どころ",
    medalsAria: "今回の勲章",
    detailOpen: "詳細を開く",
    detailClose: "詳細を閉じる",
    bestScore: "この端末の最高スコア",
    scoreBreakdown: "スコア内訳",
    thanks: "また配達に来てね。",
    shareLead: "バッグを集めて、家へ配達。",
    shareSub: "スマホで遊べる無料ゲーム",
    shareTagline: "今日も、のんびり急ぐ。",
    deliveryCount: "配達数",
    maxCombo: "最大連便",
    clock: "時計",
    shellGuard: "甲羅守り",
    magnet: "磁石",
    tailwind: "追い風",
    airplane: "ひこうき",
    star: "星",
    collisionCount: "接触数",
    bumps: "ぶつかった数",
    nearMiss: "すれすれ回避",
    totalDeliveries: "総配達数",
    totalPlays: "遊んだ回数",
    tool: "道具",
  }),
  itemText: Object.freeze({
    deliveryComplete: "配達完了！ +{score}",
    multiDeliveryComplete: "バッグ{count}個 配達完了！ +{score}",
    comboBanner: "{count}連便！",
    tailwindOn: "追い風！",
    secondHalf: "かめぽす急便",
    lastSpurt: "ラストスパート！",
    dailyMissionComplete: "今日のかめ便 +{score}",
    itemNotice: "{name}獲得！ {description}",
    bagNeeded: "バッグをのせてから",
    postDelivery: "ポスト便 +{score}",
    heliDelivery: "ヘリ便 +{score}",
    heliHome: "家へひとっ飛び",
    clockUse: "時計+{seconds}秒",
    clockActivated: "時計発動！ +{seconds}秒",
    gained: "{name}獲得！",
    magnetOn: "磁石オン",
    flightUse: "ひとっ飛び",
    clockBonus: "+{score} / 時間+{seconds}秒",
    starBonus: "星 +{score}",
    fastBonus: "早便 +{score}",
    multiBonus: "まとめ便 +{score}",
  }),
  itemDescriptions: Object.freeze({
    clock: "拾うとすぐ時間プラス",
    shield: "1回だけぶつかっても平気",
    magnet: "近くのバッグを引き寄せる",
    turbo: "少しの間すばやく走る",
    flight: "道をひとっ飛びできる",
  }),
  nextMoves: Object.freeze({
    firstLabel: "まずは",
    firstValue: "バッグを甲羅へ",
    deliveryCount: "配達数",
    shellGuardValue: "危ない前に使う",
    multiDelivery: "まとめ便",
    multiDeliveryValue: "2個のせて届ける",
    toolPickup: "道具拾い",
    toolPickupValue: "見えたら寄る",
    clockValue: "拾うとすぐ時間プラス",
    nearMiss: "すれすれ",
    nearMissValue: "輪の外をかすめる",
    retryValue: "今日の街を走る",
  }),
  resultTips: Object.freeze({
    firstBag: "黄色線を追うとバッグに着きます。",
    shield: "危ない道の前で甲羅守り。1回だけ守れます。",
    multiDelivery: "近いバッグを2個、甲羅にのせて届けると伸びます。",
    toolPickup: "道具は見えたら拾う。磁石は特に便利です。",
    clock: "時計は拾った瞬間に時間が増えます。",
    combo: "3件続けて届けると追い風が入ります。",
    flight: "ひこうきは工事や電気を越えたい時に使えます。",
    shortcut: "追い風とワープで、カメ配達員の近道を作ろう。",
    nearMiss: "危ない輪の外側をかすめると少し加点。",
    toolUse: "道具を使い切ると、かめぽす便のスコアがもう一段伸びます。",
  }),
  scoreBreakdown: Object.freeze({
    delivery: "配達スコア",
    fastMulti: "早便とまとめ便",
    bonus: "ボーナススコア",
    penalty: "減点スコア",
    next: "次回",
  }),
  rankingText: Object.freeze({
    firstPlace: "1位",
    firstNow: "今のところ1位",
    firstKeep: "1位キープ中",
    rank: "{rank}位",
    rankTarget: "{rank}位まで",
    rankGap: "あと{score}で{rank}位",
    topGap: "1位との差 {score}",
    currentPrefix: "今回 / ",
    meta: "{deliveries}便 / {combo}連便",
    empty: "まだ記録なし",
  }),
  medals: Object.freeze({
    heading: "勲章",
    noCollision: "無接触",
    noCollisionDescription: "ぶつからずに完走",
  }),
  hudText: Object.freeze({
    oneMore: "あと1",
  }),
  guideRules: Object.freeze({
    pickup: "黄色線はバッグへの道",
    delivery: "赤線は家への道",
    goal: "たくさん配達してスコアを伸ばそう",
  }),
});
